# Spring data source setting
spring:
  datasource:
#    type: org.apache.commons.dbcp.basicDatasource
    drive-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?userUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false
#    url: jdbc:mysql://localhost:3306/demo?userUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false
    username: root
    password: root
    initialSizt: 10
    maxActive: 100
    minIdle: 3
    maxWait: 5000

# MyBatis setting
# 当mapper和xml文件不在同级目录下时，需要配置该文件的扫描路径，classpath：后直接跟DemoApplicaiton的同级目录路径
#mybatis:
#  mapper-locations:
#  type-aliases-package:


# log4j setting
logging:
  config: classpath:static/log4j2.xml
  file:
    path: C:/Users/Leo/Desktop/logs

# druid recycle
druid:
  removeAbandoned: true
  removeAbandonedTimeout: 300
  logAbandoned: true

server:
  port: 8080